receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  elasticsearch/trace:
    endpoints: [https://host.docker.internal:9200]
    user: elastic
    api_key: UXhMMkZwTUJZOXJGRG8yODdlZzU6VU5qX2VJLVNSVDI0M0VxWVY4N2VSdw== 
    traces_index: otel_trace_index
    tls:
      insecure_skip_verify: true
  elasticsearch/log:
    endpoints: [https://host.docker.internal:9200]
    user: elastic
    api_key: UXhMMkZwTUJZOXJGRG8yODdlZzU6VU5qX2VJLVNSVDI0M0VxWVY4N2VSdw== 
    logs_index: otel_log_index
    tls:
      insecure_skip_verify: true
  elasticsearch/metric:
    endpoints: [https://host.docker.internal:9200]
    user: elastic
    api_key: UXhMMkZwTUJZOXJGRG8yODdlZzU6VU5qX2VJLVNSVDI0M0VxWVY4N2VSdw== 
    index: otel_metric_index
    tls:
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elasticsearch/trace]
    metrics:
      receivers: [otlp]
      exporters: [elasticsearch/metric]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch/log]
