site_name: Yggdrasil Reference Guide
nav:
- HOME: README.md
- SUMMARY: SUMMARY.md
- 'I. Yggdrasil Documentation': 'Chapter I/I. Yggdrasil Documentation.md'
- 'II. Getting Started': 'Chapter II/II. Getting Started.md'
- 'III. Using Yggdrasil': 'Chapter III/III. Using Yggdrasil.md'
- 'IV. Yggdrasil Features':
    - Introduction: 'Chapter IV/IV. Yggdrasil Features.md'
    - '4.1. Modules': 'Chapter IV/4.1. Modules.md'
    - '4.1.1. yggdrasil-parent': 'Chapter IV/4.1.1. yggdrasil-parent.md'
    - '4.1.2. yggdrasil-annotation': 'Chapter IV/4.1.2. yggdrasil-annotation.md'
    - '4.1.3. yggdrasil-bean': 'Chapter IV/4.1.3. yggdrasil-bean.md'
    - '4.1.4. yggdrasil-configuration': 'Chapter IV/4.1.4. yggdrasil-configuration.md'
    - '4.1.5. yggdrasil-utils': 'Chapter IV/4.1.5. yggdrasil-utils.md'
    - '4.1.6. yggdrasil-apollo-spring-boot-starter': 'Chapter IV/4.1.6. yggdrasil-apollo-spring-boot-starter.md'
    - '4.1.7. yggdrasil-datasource-spring-boot-starter': 'Chapter IV/4.1.7. yggdrasil-datasource-spring-boot-starter.md'
    - '4.1.8. yggdrasil-redis-spring-boot-starter': 'Chapter IV/4.1.8. yggdrasil-redis-spring-boot-starter.md'
    - '4.1.9. yggdrasil-cache-spring-boot-starter': 'Chapter IV/4.1.9. yggdrasil-cache-spring-boot-starter.md'
theme: readthedocs
site_author: KehwZwei