yggdrasil: 
  datasource: 
    enable: true
    tableDefinePackages: 
    - org.s3s3l.yggdrasil.sample.dss
    requiredInstances: 
    - test
    dbs:
      test:
        autoCreate: 
          enable: true
        driverClassName: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:file:./db/test
        username: test
        password: test
        jmxEnabled: false
        testWhileIdle: false
        validationQuery: SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
        testOnBorrow: true
        testOnReturn: false
        validationInterval: 30000
        timeBetweenEvictionRunsMillis: 10000
        maxActive: 10
        maxIdle: 2
        minIdle: 1
        initialSize: 2
        maxWait: 60000
        removeAbandoned: true
        logAbandoned: true
        minEvictableIdleTimeMillis: 60000
        removeAbandonedTimeout: 60000