yggdrasil: 
  datasource: 
    enable: true
    meta: 
      tableDefinePackages: 
      - io.github.s3s3l.yggdrasil.sample.dss.condition
      - io.github.s3s3l.yggdrasil.sample.dss.dao
      proxy-define-packages:
      - io.github.s3s3l.yggdrasil.sample.dss.proxy
      proxy-config-locations:
      - proxy
      validatorFactory: io.github.s3s3l.yggdrasil.orm.validator.DefaultValidatorFactory
      typeHandlerManager: io.github.s3s3l.yggdrasil.orm.handler.TypeHandlerManager
      scanner: io.github.s3s3l.yggdrasil.utils.reflect.scan.ClassScanner
    requiredInstances: 
    - test
    mybatis:
      check-config-location: true
      config: config/mybatis-config.xml
      mapper-locations: config/mapper/**/*.xml
      type-aliases-package: io.github.s3s3l.yggdrasil.sample.dss.dao
      mapper-packages:
        test: io.github.s3s3l.yggdrasil.sample.dss.mapper
    dbs:
      test:
        autoCreate: 
          enable: true
        driverClassName: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:file:./db/test
        username: test
        password: test
        jmxEnabled: false
        testWhileIdle: false
        validationQuery: SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
        testOnBorrow: true
        testOnReturn: false
        validationInterval: 30000
        timeBetweenEvictionRunsMillis: 10000
        maxActive: 10
        maxIdle: 2
        minIdle: 1
        initialSize: 2
        maxWait: 60000
        removeAbandoned: true
        logAbandoned: true
        minEvictableIdleTimeMillis: 60000
        removeAbandonedTimeout: 60000
        meta: 
          proxy-define-packages:
          - io.github.s3s3l.yggdrasil.sample.dss.proxy
          proxy-config-locations:
          - proxy