spring: 
  application: 
    name: trace-sample
server:
  port: 20080
es:
  endpoint: https://localhost:9200
  api-key: NHVwQmRKSUJQTktEV0NpLWNKY0Q6MlVNU2hiQ0ZSdEMxTW0wYW9VNS1Fdw==
management:
  endpoints:
    web: 
      exposure: 
        include: "*"
  endpoint: 
    health: 
      show: 
        details: always